// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pingpong.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Ping struct {
	Greeting string `protobuf:"bytes,1,opt,name=Greeting,proto3" json:"Greeting,omitempty"`
}

func (m *Ping) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Ping) String() string            { _ = "STUB: not implemented"; return "" }
func (*Ping) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Ping) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Ping) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Ping) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Ping) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Ping) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetGreeting() string { _ = "STUB: not implemented"; return "" }

type Pong struct {
	Response string `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (m *Pong) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Pong) String() string            { _ = "STUB: not implemented"; return "" }
func (*Pong) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Pong) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Pong) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Pong) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Pong) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Pong) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetResponse() string { _ = "STUB: not implemented"; return "" }

func init() {
	proto.RegisterType((*Ping)(nil), "pingpong.Ping")
	proto.RegisterType((*Pong)(nil), "pingpong.Pong")
}

func init() { proto.RegisterFile("pingpong.proto", fileDescriptor_1cfbf639ab46154b) }

var fileDescriptor_1cfbf639ab46154b = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xc8, 0xcc, 0x4b,
	0x2f, 0xc8, 0xcf, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x94,
	0xb8, 0x58, 0x02, 0x32, 0xf3, 0xd2, 0x85, 0xa4, 0xb8, 0x38, 0xdc, 0x8b, 0x52, 0x53, 0x4b, 0x32,
	0xf3, 0xd2, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0xb0, 0x9a, 0x7c, 0x88, 0x9a,
	0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x98, 0x1a, 0x18, 0xdf, 0x49, 0xe6, 0xc4, 0x23,
	0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e, 0xe1, 0xc2,
	0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0x98, 0x0a, 0x92, 0x92, 0xd8, 0xc0, 0xd6, 0x1a,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x08, 0xee, 0x5c, 0x58, 0x88, 0x00, 0x00, 0x00,
}

func (m *Ping) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Ping) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Ping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Pong) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Pong) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Pong) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintPingpong(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *Ping) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Pong) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovPingpong(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozPingpong(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Ping) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Pong) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipPingpong(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthPingpong        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPingpong          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPingpong = fmt.Errorf("proto: unexpected end of group")
)
