// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: status.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Get message indicate interest in receiving a node Snapshot.
type Get struct {
}

func (m *Get) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Get) String() string            { _ = "STUB: not implemented"; return "" }
func (*Get) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Get) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Get) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Get) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Get) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Get) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Get) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Get proto.InternalMessageInfo

// Snapshot message is a response to the Get message and contains
// the appropriate values that are a snapshot of the current state
// of the running node.
type Snapshot struct {
	ReserveSize             uint64            `protobuf:"varint,1,opt,name=ReserveSize,proto3" json:"ReserveSize,omitempty"`
	PullsyncRate            float64           `protobuf:"fixed64,2,opt,name=PullsyncRate,proto3" json:"PullsyncRate,omitempty"`
	StorageRadius           uint32            `protobuf:"varint,3,opt,name=StorageRadius,proto3" json:"StorageRadius,omitempty"`
	ConnectedPeers          uint64            `protobuf:"varint,4,opt,name=ConnectedPeers,proto3" json:"ConnectedPeers,omitempty"`
	NeighborhoodSize        uint64            `protobuf:"varint,5,opt,name=NeighborhoodSize,proto3" json:"NeighborhoodSize,omitempty"`
	BeeMode                 string            `protobuf:"bytes,6,opt,name=BeeMode,proto3" json:"BeeMode,omitempty"`
	BatchCommitment         uint64            `protobuf:"varint,7,opt,name=BatchCommitment,proto3" json:"BatchCommitment,omitempty"`
	IsReachable             bool              `protobuf:"varint,8,opt,name=IsReachable,proto3" json:"IsReachable,omitempty"`
	ReserveSizeWithinRadius uint64            `protobuf:"varint,9,opt,name=ReserveSizeWithinRadius,proto3" json:"ReserveSizeWithinRadius,omitempty"`
	LastSyncedBlock         uint64            `protobuf:"varint,10,opt,name=LastSyncedBlock,proto3" json:"LastSyncedBlock,omitempty"`
	CommittedDepth          uint32            `protobuf:"varint,11,opt,name=CommittedDepth,proto3" json:"CommittedDepth,omitempty"`
	Metrics                 map[string]string `protobuf:"bytes,12,rep,name=Metrics,proto3" json:"Metrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Snapshot) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Snapshot) String() string            { _ = "STUB: not implemented"; return "" }
func (*Snapshot) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Snapshot) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Snapshot) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Snapshot) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Snapshot) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Snapshot) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetReserveSize() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Snapshot) GetPullsyncRate() float64 { _ = "STUB: not implemented"; return 0 }

func (m *Snapshot) GetStorageRadius() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *Snapshot) GetConnectedPeers() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Snapshot) GetNeighborhoodSize() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Snapshot) GetBeeMode() string { _ = "STUB: not implemented"; return "" }

func (m *Snapshot) GetBatchCommitment() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Snapshot) GetIsReachable() bool { _ = "STUB: not implemented"; return false }

func (m *Snapshot) GetReserveSizeWithinRadius() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Snapshot) GetLastSyncedBlock() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Snapshot) GetCommittedDepth() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *Snapshot) GetMetrics() map[string]string { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*Get)(nil), "status.Get")
	proto.RegisterType((*Snapshot)(nil), "status.Snapshot")
	proto.RegisterMapType((map[string]string)(nil), "status.Snapshot.MetricsEntry")
}

func init() { proto.RegisterFile("status.proto", fileDescriptor_dfe4fce6682daf5b) }

var fileDescriptor_dfe4fce6682daf5b = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x8a, 0xd4, 0x40,
	0x10, 0xc6, 0xa7, 0xe7, 0xff, 0xd4, 0xcc, 0xea, 0xd2, 0x08, 0x36, 0xa2, 0x21, 0x0c, 0x22, 0xc1,
	0xc3, 0x1c, 0xf4, 0xe0, 0xb2, 0xc7, 0x59, 0x45, 0x04, 0x57, 0x96, 0x9e, 0x83, 0xe0, 0xad, 0x93,
	0x14, 0x9b, 0xb0, 0x99, 0xee, 0x90, 0xae, 0x2c, 0xc4, 0xa7, 0xf0, 0x55, 0x7c, 0x0b, 0x8f, 0x7b,
	0xf4, 0x28, 0x33, 0x2f, 0x22, 0xe9, 0xcc, 0x40, 0x26, 0xe2, 0xad, 0xeb, 0x57, 0x45, 0xf5, 0xd7,
	0xdf, 0xd7, 0xb0, 0xb0, 0xa4, 0xa8, 0xb4, 0xab, 0xbc, 0x30, 0x64, 0xf8, 0xb8, 0xa9, 0x96, 0x23,
	0x18, 0x7c, 0x44, 0x5a, 0xfe, 0x1c, 0xc2, 0x74, 0xa3, 0x55, 0x6e, 0x13, 0x43, 0xdc, 0x87, 0xb9,
	0x44, 0x8b, 0xc5, 0x3d, 0x6e, 0xd2, 0xef, 0x28, 0x98, 0xcf, 0x82, 0xa1, 0x6c, 0x23, 0xbe, 0x84,
	0xc5, 0x4d, 0x99, 0x65, 0xb6, 0xd2, 0x91, 0x54, 0x84, 0xa2, 0xef, 0xb3, 0x80, 0xc9, 0x13, 0xc6,
	0x5f, 0xc2, 0xd9, 0x86, 0x4c, 0xa1, 0x6e, 0x51, 0xaa, 0x38, 0x2d, 0xad, 0x18, 0xf8, 0x2c, 0x38,
	0x93, 0xa7, 0x90, 0xbf, 0x82, 0x47, 0x57, 0x46, 0x6b, 0x8c, 0x08, 0xe3, 0x1b, 0xc4, 0xc2, 0x8a,
	0xa1, 0xbb, 0xae, 0x43, 0xf9, 0x6b, 0x38, 0xff, 0x82, 0xe9, 0x6d, 0x12, 0x9a, 0x22, 0x31, 0x26,
	0x76, 0xc2, 0x46, 0x6e, 0xf2, 0x1f, 0xce, 0x05, 0x4c, 0xd6, 0x88, 0xd7, 0x26, 0x46, 0x31, 0xf6,
	0x59, 0x30, 0x93, 0xc7, 0x92, 0x07, 0xf0, 0x78, 0xad, 0x28, 0x4a, 0xae, 0xcc, 0x76, 0x9b, 0xd2,
	0x16, 0x35, 0x89, 0x89, 0x5b, 0xd2, 0xc5, 0xb5, 0x07, 0x9f, 0xac, 0x44, 0x15, 0x25, 0x2a, 0xcc,
	0x50, 0x4c, 0x7d, 0x16, 0x4c, 0x65, 0x1b, 0xf1, 0x0b, 0x78, 0xda, 0xb2, 0xe4, 0x6b, 0x4a, 0x49,
	0xaa, 0x0f, 0x2f, 0x9d, 0xb9, 0x9d, 0xff, 0x6b, 0xd7, 0x2a, 0x3e, 0x2b, 0x4b, 0x9b, 0x4a, 0x47,
	0x18, 0xaf, 0x33, 0x13, 0xdd, 0x09, 0x68, 0x54, 0x74, 0x70, 0xe3, 0x4e, 0xad, 0x89, 0x30, 0x7e,
	0x8f, 0x39, 0x25, 0x62, 0xee, 0x4c, 0xec, 0x50, 0xfe, 0x0e, 0x26, 0xd7, 0x48, 0x45, 0x1a, 0x59,
	0xb1, 0xf0, 0x07, 0xc1, 0xfc, 0xcd, 0x8b, 0xd5, 0x21, 0xed, 0x63, 0xa8, 0xab, 0x43, 0xff, 0x83,
	0xa6, 0xa2, 0x92, 0xc7, 0xe9, 0x67, 0x97, 0xb0, 0x68, 0x37, 0xf8, 0x39, 0x0c, 0xee, 0xb0, 0x72,
	0x91, 0xcf, 0x64, 0x7d, 0xe4, 0x4f, 0x60, 0x74, 0xaf, 0xb2, 0xb2, 0xc9, 0x78, 0x26, 0x9b, 0xe2,
	0xb2, 0x7f, 0xc1, 0xd6, 0xcf, 0x7f, 0xed, 0x3c, 0xf6, 0xb0, 0xf3, 0xd8, 0x9f, 0x9d, 0xc7, 0x7e,
	0xec, 0xbd, 0xde, 0xc3, 0xde, 0xeb, 0xfd, 0xde, 0x7b, 0xbd, 0x6f, 0xfd, 0x3c, 0x0c, 0xc7, 0xee,
	0x9f, 0xbd, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x23, 0x3c, 0xa8, 0x9b, 0x77, 0x02, 0x00, 0x00,
}

func (m *Get) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Get) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Get) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Snapshot) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Snapshot) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Snapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintStatus(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *Get) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Snapshot) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovStatus(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozStatus(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Get) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Snapshot) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipStatus(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthStatus        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStatus          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStatus = fmt.Errorf("proto: unexpected end of group")
)
