// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: handshake.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Syn struct {
	ObservedUnderlay []byte `protobuf:"bytes,1,opt,name=ObservedUnderlay,proto3" json:"ObservedUnderlay,omitempty"`
}

func (m *Syn) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Syn) String() string            { _ = "STUB: not implemented"; return "" }
func (*Syn) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Syn) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Syn) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Syn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Syn) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Syn) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Syn) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Syn proto.InternalMessageInfo

func (m *Syn) GetObservedUnderlay() []byte { _ = "STUB: not implemented"; return nil }

type Ack struct {
	Address        *BzzAddress `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	NetworkID      uint64      `protobuf:"varint,2,opt,name=NetworkID,proto3" json:"NetworkID,omitempty"`
	FullNode       bool        `protobuf:"varint,3,opt,name=FullNode,proto3" json:"FullNode,omitempty"`
	Nonce          []byte      `protobuf:"bytes,4,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	WelcomeMessage string      `protobuf:"bytes,99,opt,name=WelcomeMessage,proto3" json:"WelcomeMessage,omitempty"`
}

func (m *Ack) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Ack) String() string            { _ = "STUB: not implemented"; return "" }
func (*Ack) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Ack) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Ack) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Ack) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Ack) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Ack) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetAddress() *BzzAddress { _ = "STUB: not implemented"; return nil }

func (m *Ack) GetNetworkID() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Ack) GetFullNode() bool { _ = "STUB: not implemented"; return false }

func (m *Ack) GetNonce() []byte { _ = "STUB: not implemented"; return nil }

func (m *Ack) GetWelcomeMessage() string { _ = "STUB: not implemented"; return "" }

type SynAck struct {
	Syn *Syn `protobuf:"bytes,1,opt,name=Syn,proto3" json:"Syn,omitempty"`
	Ack *Ack `protobuf:"bytes,2,opt,name=Ack,proto3" json:"Ack,omitempty"`
}

func (m *SynAck) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SynAck) String() string            { _ = "STUB: not implemented"; return "" }
func (*SynAck) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SynAck) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SynAck) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SynAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SynAck) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SynAck) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SynAck) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SynAck proto.InternalMessageInfo

func (m *SynAck) GetSyn() *Syn { _ = "STUB: not implemented"; return nil }

func (m *SynAck) GetAck() *Ack { _ = "STUB: not implemented"; return nil }

type BzzAddress struct {
	Underlay  []byte `protobuf:"bytes,1,opt,name=Underlay,proto3" json:"Underlay,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Overlay   []byte `protobuf:"bytes,3,opt,name=Overlay,proto3" json:"Overlay,omitempty"`
}

func (m *BzzAddress) Reset()                    { _ = "STUB: not implemented"; return }
func (m *BzzAddress) String() string            { _ = "STUB: not implemented"; return "" }
func (*BzzAddress) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*BzzAddress) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *BzzAddress) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BzzAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BzzAddress) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *BzzAddress) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *BzzAddress) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_BzzAddress proto.InternalMessageInfo

func (m *BzzAddress) GetUnderlay() []byte { _ = "STUB: not implemented"; return nil }

func (m *BzzAddress) GetSignature() []byte { _ = "STUB: not implemented"; return nil }

func (m *BzzAddress) GetOverlay() []byte { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*Syn)(nil), "handshake.Syn")
	proto.RegisterType((*Ack)(nil), "handshake.Ack")
	proto.RegisterType((*SynAck)(nil), "handshake.SynAck")
	proto.RegisterType((*BzzAddress)(nil), "handshake.BzzAddress")
}

func init() { proto.RegisterFile("handshake.proto", fileDescriptor_a77305914d5d202f) }

var fileDescriptor_a77305914d5d202f = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x3b, 0x4d, 0xed, 0xcf, 0xb5, 0x54, 0x19, 0x14, 0x82, 0x94, 0x10, 0xb2, 0x90, 0xe0,
	0xa2, 0xa2, 0x3e, 0x41, 0x8b, 0x08, 0x82, 0xb6, 0x30, 0x41, 0x04, 0x57, 0xa6, 0x99, 0x4b, 0x2b,
	0x89, 0x33, 0x65, 0xa6, 0xad, 0xa4, 0x4f, 0xe1, 0x93, 0xf8, 0x1c, 0x2e, 0xbb, 0x74, 0x29, 0xed,
	0x8b, 0x48, 0xa6, 0x3f, 0xd1, 0xba, 0x3c, 0xe7, 0x9e, 0x99, 0xf9, 0xce, 0x1d, 0x38, 0x18, 0x86,
	0x82, 0xeb, 0x61, 0x18, 0x63, 0x6b, 0xa4, 0xe4, 0x58, 0xd2, 0xda, 0xd6, 0xf0, 0x2e, 0xc0, 0x0a,
	0x52, 0x41, 0xcf, 0xe0, 0xb0, 0xd7, 0xd7, 0xa8, 0xa6, 0xc8, 0x1f, 0x04, 0x47, 0x95, 0x84, 0xa9,
	0x4d, 0x5c, 0xe2, 0xd7, 0xd9, 0x3f, 0xdf, 0xfb, 0x20, 0x60, 0xb5, 0xa3, 0x98, 0x9e, 0x43, 0xa5,
	0xcd, 0xb9, 0x42, 0xad, 0x4d, 0x74, 0xff, 0xf2, 0xb8, 0x95, 0x3f, 0xd4, 0x99, 0xcd, 0xd6, 0x43,
	0xb6, 0x49, 0xd1, 0x26, 0xd4, 0xba, 0x38, 0x7e, 0x93, 0x2a, 0xbe, 0xbd, 0xb6, 0x8b, 0x2e, 0xf1,
	0x4b, 0x2c, 0x37, 0xe8, 0x09, 0x54, 0x6f, 0x26, 0x49, 0xd2, 0x95, 0x1c, 0x6d, 0xcb, 0x25, 0x7e,
	0x95, 0x6d, 0x35, 0x3d, 0x82, 0xbd, 0xae, 0x14, 0x11, 0xda, 0x25, 0xc3, 0xb4, 0x12, 0xf4, 0x14,
	0x1a, 0x8f, 0x98, 0x44, 0xf2, 0x15, 0xef, 0x51, 0xeb, 0x70, 0x80, 0x76, 0xe4, 0x12, 0xbf, 0xc6,
	0x76, 0x5c, 0xef, 0x0e, 0xca, 0x41, 0x2a, 0x32, 0x64, 0xd7, 0xb4, 0x5d, 0xe3, 0x36, 0x7e, 0xe1,
	0x06, 0xa9, 0x60, 0x66, 0x11, 0xae, 0xe9, 0x66, 0xe8, 0xfe, 0x26, 0xda, 0x51, 0xcc, 0xb2, 0x91,
	0xf7, 0x0c, 0x90, 0x97, 0xcb, 0xa8, 0x77, 0x16, 0xb6, 0xd5, 0x59, 0xdf, 0xe0, 0x65, 0x20, 0xc2,
	0xf1, 0x44, 0xa1, 0xb9, 0xb1, 0xce, 0x72, 0x83, 0xda, 0x50, 0xe9, 0x4d, 0x57, 0x07, 0x2d, 0x33,
	0xdb, 0xc8, 0x4e, 0xf3, 0x73, 0xe1, 0x90, 0xf9, 0xc2, 0x21, 0xdf, 0x0b, 0x87, 0xbc, 0x2f, 0x9d,
	0xc2, 0x7c, 0xe9, 0x14, 0xbe, 0x96, 0x4e, 0xe1, 0xa9, 0x38, 0xea, 0xf7, 0xcb, 0xe6, 0x0f, 0xaf,
	0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x87, 0xa7, 0x49, 0x00, 0xd6, 0x01, 0x00, 0x00,
}

func (m *Syn) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Syn) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Syn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Ack) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Ack) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Ack) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SynAck) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *SynAck) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *SynAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BzzAddress) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *BzzAddress) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *BzzAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintHandshake(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *Syn) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Ack) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SynAck) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BzzAddress) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovHandshake(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozHandshake(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Syn) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Ack) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SynAck) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BzzAddress) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipHandshake(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthHandshake        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHandshake          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHandshake = fmt.Errorf("proto: unexpected end of group")
)
