// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: swap.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EmitCheque struct {
	Cheque []byte `protobuf:"bytes,1,opt,name=Cheque,proto3" json:"Cheque,omitempty"`
}

func (m *EmitCheque) Reset()                    { _ = "STUB: not implemented"; return }
func (m *EmitCheque) String() string            { _ = "STUB: not implemented"; return "" }
func (*EmitCheque) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*EmitCheque) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *EmitCheque) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *EmitCheque) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *EmitCheque) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *EmitCheque) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *EmitCheque) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_EmitCheque proto.InternalMessageInfo

func (m *EmitCheque) GetCheque() []byte { _ = "STUB: not implemented"; return nil }

type Handshake struct {
	Beneficiary []byte `protobuf:"bytes,1,opt,name=Beneficiary,proto3" json:"Beneficiary,omitempty"`
}

func (m *Handshake) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Handshake) String() string            { _ = "STUB: not implemented"; return "" }
func (*Handshake) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Handshake) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Handshake) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Handshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Handshake) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Handshake) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Handshake) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Handshake proto.InternalMessageInfo

func (m *Handshake) GetBeneficiary() []byte { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*EmitCheque)(nil), "swapprotocol.EmitCheque")
	proto.RegisterType((*Handshake)(nil), "swapprotocol.Handshake")
}

func init() { proto.RegisterFile("swap.proto", fileDescriptor_c35a3890a6e60fb7) }

var fileDescriptor_c35a3890a6e60fb7 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2e, 0x4f, 0x2c,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0xb1, 0xc1, 0xcc, 0xe4, 0xfc, 0x1c, 0x25,
	0x15, 0x2e, 0x2e, 0xd7, 0xdc, 0xcc, 0x12, 0xe7, 0x8c, 0xd4, 0xc2, 0xd2, 0x54, 0x21, 0x31, 0x2e,
	0x36, 0x08, 0x4b, 0x82, 0x51, 0x81, 0x51, 0x83, 0x27, 0x08, 0xca, 0x53, 0xd2, 0xe5, 0xe2, 0xf4,
	0x48, 0xcc, 0x4b, 0x29, 0xce, 0x48, 0xcc, 0x4e, 0x15, 0x52, 0xe0, 0xe2, 0x76, 0x4a, 0xcd, 0x4b,
	0x4d, 0xcb, 0x4c, 0xce, 0x4c, 0x2c, 0xaa, 0x84, 0xaa, 0x44, 0x16, 0x72, 0x92, 0x39, 0xf1, 0x48,
	0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0,
	0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0xa6, 0x82, 0xa4, 0x24, 0x36, 0xb0, 0xe5, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xdd, 0x22, 0xd8, 0x95, 0x00, 0x00, 0x00,
}

func (m *EmitCheque) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *EmitCheque) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *EmitCheque) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Handshake) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Handshake) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Handshake) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintSwap(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *EmitCheque) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Handshake) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovSwap(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozSwap(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *EmitCheque) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Handshake) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipSwap(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthSwap        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSwap          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSwap = fmt.Errorf("proto: unexpected end of group")
)
