// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: headers.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Headers struct {
	Headers []*Header `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
}

func (m *Headers) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Headers) String() string            { _ = "STUB: not implemented"; return "" }
func (*Headers) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Headers) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Headers) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Headers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Headers) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Headers) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Headers) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Headers proto.InternalMessageInfo

func (m *Headers) GetHeaders() []*Header { _ = "STUB: not implemented"; return nil }

type Header struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Header) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Header) String() string            { _ = "STUB: not implemented"; return "" }
func (*Header) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Header) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Header) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Header) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Header) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Header) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetKey() string { _ = "STUB: not implemented"; return "" }

func (m *Header) GetValue() []byte { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*Headers)(nil), "headers.Headers")
	proto.RegisterType((*Header)(nil), "headers.Header")
}

func init() { proto.RegisterFile("headers.proto", fileDescriptor_9cec2a7af668f07b) }

var fileDescriptor_9cec2a7af668f07b = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x48, 0x4d, 0x4c,
	0x49, 0x2d, 0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x4c, 0xb8,
	0xd8, 0x3d, 0x20, 0x4c, 0x21, 0x4d, 0x2e, 0x98, 0xa8, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x11,
	0xbf, 0x1e, 0x4c, 0x13, 0x44, 0x49, 0x10, 0x5c, 0x97, 0x01, 0x17, 0x1b, 0x44, 0x48, 0x48, 0x80,
	0x8b, 0x39, 0x3b, 0xb5, 0x52, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x14, 0x12, 0xe1,
	0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x09, 0x82, 0x70, 0x9c,
	0x64, 0x4e, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f,
	0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0x8a, 0xa9, 0x20, 0x29, 0x89,
	0x0d, 0xec, 0x2a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x8f, 0xd4, 0x36, 0xa6, 0x00,
	0x00, 0x00,
}

func (m *Headers) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Headers) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Headers) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Header) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Header) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Header) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintHeaders(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *Headers) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Header) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovHeaders(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozHeaders(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Headers) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Header) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipHeaders(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthHeaders        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHeaders          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHeaders = fmt.Errorf("proto: unexpected end of group")
)
