// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pullsync.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Syn struct {
}

func (m *Syn) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Syn) String() string            { _ = "STUB: not implemented"; return "" }
func (*Syn) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Syn) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Syn) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Syn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Syn) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Syn) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Syn) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Syn proto.InternalMessageInfo

type Ack struct {
	Cursors []uint64 `protobuf:"varint,1,rep,packed,name=Cursors,proto3" json:"Cursors,omitempty"`
	Epoch   uint64   `protobuf:"varint,2,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
}

func (m *Ack) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Ack) String() string            { _ = "STUB: not implemented"; return "" }
func (*Ack) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Ack) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Ack) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Ack) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Ack) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Ack) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetCursors() []uint64 { _ = "STUB: not implemented"; return nil }

func (m *Ack) GetEpoch() uint64 { _ = "STUB: not implemented"; return 0 }

type Get struct {
	Bin   int32  `protobuf:"varint,1,opt,name=Bin,proto3" json:"Bin,omitempty"`
	Start uint64 `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
}

func (m *Get) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Get) String() string            { _ = "STUB: not implemented"; return "" }
func (*Get) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Get) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Get) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Get) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Get) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Get) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Get) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Get proto.InternalMessageInfo

func (m *Get) GetBin() int32 { _ = "STUB: not implemented"; return 0 }

func (m *Get) GetStart() uint64 { _ = "STUB: not implemented"; return 0 }

type Chunk struct {
	Address   []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	BatchID   []byte `protobuf:"bytes,2,opt,name=BatchID,proto3" json:"BatchID,omitempty"`
	StampHash []byte `protobuf:"bytes,3,opt,name=StampHash,proto3" json:"StampHash,omitempty"`
}

func (m *Chunk) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Chunk) String() string            { _ = "STUB: not implemented"; return "" }
func (*Chunk) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Chunk) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Chunk) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Chunk) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Chunk) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Chunk) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetAddress() []byte { _ = "STUB: not implemented"; return nil }

func (m *Chunk) GetBatchID() []byte { _ = "STUB: not implemented"; return nil }

func (m *Chunk) GetStampHash() []byte { _ = "STUB: not implemented"; return nil }

type Offer struct {
	Topmost uint64   `protobuf:"varint,1,opt,name=Topmost,proto3" json:"Topmost,omitempty"`
	Chunks  []*Chunk `protobuf:"bytes,2,rep,name=Chunks,proto3" json:"Chunks,omitempty"`
}

func (m *Offer) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Offer) String() string            { _ = "STUB: not implemented"; return "" }
func (*Offer) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Offer) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Offer) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Offer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Offer) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Offer) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Offer) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Offer proto.InternalMessageInfo

func (m *Offer) GetTopmost() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Offer) GetChunks() []*Chunk { _ = "STUB: not implemented"; return nil }

type Want struct {
	BitVector []byte `protobuf:"bytes,1,opt,name=BitVector,proto3" json:"BitVector,omitempty"`
}

func (m *Want) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Want) String() string            { _ = "STUB: not implemented"; return "" }
func (*Want) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Want) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Want) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Want) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Want) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Want) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Want) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Want proto.InternalMessageInfo

func (m *Want) GetBitVector() []byte { _ = "STUB: not implemented"; return nil }

type Delivery struct {
	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Stamp   []byte `protobuf:"bytes,3,opt,name=Stamp,proto3" json:"Stamp,omitempty"`
}

func (m *Delivery) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Delivery) String() string            { _ = "STUB: not implemented"; return "" }
func (*Delivery) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Delivery) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Delivery) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Delivery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Delivery) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Delivery) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Delivery) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Delivery proto.InternalMessageInfo

func (m *Delivery) GetAddress() []byte { _ = "STUB: not implemented"; return nil }

func (m *Delivery) GetData() []byte { _ = "STUB: not implemented"; return nil }

func (m *Delivery) GetStamp() []byte { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*Syn)(nil), "pullsync.Syn")
	proto.RegisterType((*Ack)(nil), "pullsync.Ack")
	proto.RegisterType((*Get)(nil), "pullsync.Get")
	proto.RegisterType((*Chunk)(nil), "pullsync.Chunk")
	proto.RegisterType((*Offer)(nil), "pullsync.Offer")
	proto.RegisterType((*Want)(nil), "pullsync.Want")
	proto.RegisterType((*Delivery)(nil), "pullsync.Delivery")
}

func init() { proto.RegisterFile("pullsync.proto", fileDescriptor_d1dee042cf9c065c) }

var fileDescriptor_d1dee042cf9c065c = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0xeb, 0x3a, 0x29, 0xe5, 0x50, 0x01, 0xb2, 0x18, 0x32, 0x54, 0x51, 0x64, 0x21, 0x91,
	0x85, 0x0e, 0x20, 0x1e, 0xa0, 0x69, 0x11, 0x97, 0x01, 0x24, 0x17, 0x81, 0x60, 0x73, 0xd3, 0x54,
	0xa9, 0x68, 0x63, 0xcb, 0x76, 0x91, 0xfa, 0x16, 0x3c, 0x16, 0x63, 0x47, 0x46, 0xd4, 0xbc, 0x08,
	0x8a, 0x1b, 0xd3, 0x8d, 0xed, 0x7c, 0xe7, 0xf6, 0xfb, 0x3f, 0x86, 0x43, 0xb9, 0x9c, 0xcf, 0xf5,
	0xaa, 0x48, 0x7b, 0x52, 0x09, 0x23, 0x48, 0xdb, 0x31, 0xf5, 0x01, 0x8f, 0x56, 0x05, 0xbd, 0x02,
	0xdc, 0x4f, 0xdf, 0x49, 0x00, 0x7b, 0x83, 0xa5, 0xd2, 0x42, 0xe9, 0x00, 0x45, 0x38, 0xf6, 0x98,
	0x43, 0x72, 0x02, 0xfe, 0xb5, 0x14, 0x69, 0x1e, 0x34, 0x23, 0x14, 0x7b, 0x6c, 0x0b, 0xf4, 0x1c,
	0xf0, 0x4d, 0x66, 0xc8, 0x31, 0xe0, 0x64, 0x56, 0x04, 0x28, 0x42, 0xb1, 0xcf, 0xaa, 0xb0, 0x6a,
	0x1f, 0x19, 0xae, 0x8c, 0x6b, 0xb7, 0x40, 0x5f, 0xc1, 0x1f, 0xe4, 0xcb, 0xc2, 0xea, 0xf4, 0x27,
	0x13, 0x95, 0x69, 0x6d, 0x87, 0x3a, 0xcc, 0x61, 0x55, 0x49, 0xb8, 0x49, 0xf3, 0xbb, 0xa1, 0x1d,
	0xed, 0x30, 0x87, 0xa4, 0x0b, 0xfb, 0x23, 0xc3, 0x17, 0xf2, 0x96, 0xeb, 0x3c, 0xc0, 0xb6, 0xb6,
	0x4b, 0xd0, 0x7b, 0xf0, 0x1f, 0xa7, 0xd3, 0x4c, 0x55, 0x0b, 0x9e, 0x84, 0x5c, 0x08, 0x6d, 0xec,
	0x6a, 0x8f, 0x39, 0x24, 0x67, 0xd0, 0xb2, 0xea, 0x3a, 0x68, 0x46, 0x38, 0x3e, 0xb8, 0x38, 0xea,
	0xfd, 0x5d, 0xc5, 0xe6, 0x59, 0x5d, 0xa6, 0xa7, 0xe0, 0xbd, 0xf0, 0xc2, 0x54, 0x8a, 0xc9, 0xcc,
	0x3c, 0x67, 0xa9, 0x11, 0xaa, 0x7e, 0xe7, 0x2e, 0x41, 0x1f, 0xa0, 0x3d, 0xcc, 0xe6, 0xb3, 0x8f,
	0x4c, 0xad, 0xfe, 0xf1, 0x43, 0xc0, 0x1b, 0x72, 0xc3, 0x6b, 0x33, 0x36, 0xae, 0x8f, 0xb3, 0x90,
	0xb5, 0x8b, 0x2d, 0x24, 0xdd, 0xaf, 0x4d, 0x88, 0xd6, 0x9b, 0x10, 0xfd, 0x6c, 0x42, 0xf4, 0x59,
	0x86, 0x8d, 0x75, 0x19, 0x36, 0xbe, 0xcb, 0xb0, 0xf1, 0xd6, 0x94, 0xe3, 0x71, 0xcb, 0x7e, 0xdc,
	0xe5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x02, 0x2f, 0x9a, 0xca, 0x01, 0x00, 0x00,
}

func (m *Syn) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Syn) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Syn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Ack) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Ack) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Ack) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Get) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Get) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Get) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Chunk) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Chunk) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Chunk) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Offer) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Offer) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Offer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Want) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Want) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Want) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Delivery) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Delivery) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Delivery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintPullsync(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *Syn) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Ack) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Get) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Chunk) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Offer) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Want) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Delivery) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovPullsync(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozPullsync(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Syn) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Ack) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Get) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Chunk) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Offer) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Want) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Delivery) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipPullsync(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthPullsync        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPullsync          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPullsync = fmt.Errorf("proto: unexpected end of group")
)
