// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hive.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Peers struct {
	Peers []*BzzAddress `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (m *Peers) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Peers) String() string            { _ = "STUB: not implemented"; return "" }
func (*Peers) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Peers) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Peers) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Peers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Peers) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Peers) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Peers) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Peers proto.InternalMessageInfo

func (m *Peers) GetPeers() []*BzzAddress { _ = "STUB: not implemented"; return nil }

type BzzAddress struct {
	Underlay  []byte `protobuf:"bytes,1,opt,name=Underlay,proto3" json:"Underlay,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Overlay   []byte `protobuf:"bytes,3,opt,name=Overlay,proto3" json:"Overlay,omitempty"`
	Nonce     []byte `protobuf:"bytes,4,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
}

func (m *BzzAddress) Reset()                    { _ = "STUB: not implemented"; return }
func (m *BzzAddress) String() string            { _ = "STUB: not implemented"; return "" }
func (*BzzAddress) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*BzzAddress) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *BzzAddress) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BzzAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BzzAddress) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *BzzAddress) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *BzzAddress) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_BzzAddress proto.InternalMessageInfo

func (m *BzzAddress) GetUnderlay() []byte { _ = "STUB: not implemented"; return nil }

func (m *BzzAddress) GetSignature() []byte { _ = "STUB: not implemented"; return nil }

func (m *BzzAddress) GetOverlay() []byte { _ = "STUB: not implemented"; return nil }

func (m *BzzAddress) GetNonce() []byte { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*Peers)(nil), "hive.Peers")
	proto.RegisterType((*BzzAddress)(nil), "hive.BzzAddress")
}

func init() { proto.RegisterFile("hive.proto", fileDescriptor_d635d1ead41ba02c) }

var fileDescriptor_d635d1ead41ba02c = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xc8, 0x2c, 0x4b,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xf4, 0xb9, 0x58, 0x03, 0x52,
	0x53, 0x8b, 0x8a, 0x85, 0xd4, 0xb8, 0x58, 0x0b, 0x40, 0x0c, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e,
	0x23, 0x01, 0x3d, 0xb0, 0x52, 0xa7, 0xaa, 0x2a, 0xc7, 0x94, 0x94, 0xa2, 0xd4, 0xe2, 0xe2, 0x20,
	0x88, 0xb4, 0x52, 0x19, 0x17, 0x17, 0x42, 0x50, 0x48, 0x8a, 0x8b, 0x23, 0x34, 0x2f, 0x25, 0xb5,
	0x28, 0x27, 0xb1, 0x52, 0x82, 0x51, 0x81, 0x51, 0x83, 0x27, 0x08, 0xce, 0x17, 0x92, 0xe1, 0xe2,
	0x0c, 0xce, 0x4c, 0xcf, 0x4b, 0x2c, 0x29, 0x2d, 0x4a, 0x95, 0x60, 0x02, 0x4b, 0x22, 0x04, 0x84,
	0x24, 0xb8, 0xd8, 0xfd, 0xcb, 0x20, 0x1a, 0x99, 0xc1, 0x72, 0x30, 0xae, 0x90, 0x08, 0x17, 0xab,
	0x5f, 0x7e, 0x5e, 0x72, 0xaa, 0x04, 0x0b, 0x58, 0x1c, 0xc2, 0x71, 0x92, 0x39, 0xf1, 0x48, 0x8e,
	0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58,
	0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0xa6, 0x82, 0xa4, 0x24, 0x36, 0xb0, 0x9f, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x40, 0x7e, 0xf9, 0x4f, 0xe1, 0x00, 0x00, 0x00,
}

func (m *Peers) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Peers) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Peers) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BzzAddress) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *BzzAddress) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *BzzAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintHive(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *Peers) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BzzAddress) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovHive(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozHive(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Peers) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BzzAddress) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipHive(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthHive        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHive          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHive = fmt.Errorf("proto: unexpected end of group")
)
