// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pricing.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AnnouncePaymentThreshold struct {
	PaymentThreshold []byte `protobuf:"bytes,1,opt,name=PaymentThreshold,proto3" json:"PaymentThreshold,omitempty"`
}

func (m *AnnouncePaymentThreshold) Reset()         { _ = "STUB: not implemented"; return }
func (m *AnnouncePaymentThreshold) String() string { _ = "STUB: not implemented"; return "" }
func (*AnnouncePaymentThreshold) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*AnnouncePaymentThreshold) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AnnouncePaymentThreshold) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *AnnouncePaymentThreshold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AnnouncePaymentThreshold) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *AnnouncePaymentThreshold) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *AnnouncePaymentThreshold) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_AnnouncePaymentThreshold proto.InternalMessageInfo

func (m *AnnouncePaymentThreshold) GetPaymentThreshold() []byte {
	_ = "STUB: not implemented"
	return nil
}

func init() {
	proto.RegisterType((*AnnouncePaymentThreshold)(nil), "pricing.AnnouncePaymentThreshold")
}

func init() { proto.RegisterFile("pricing.proto", fileDescriptor_ec4cc93d045d43d0) }

var fileDescriptor_ec4cc93d045d43d0 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0xca, 0x4c,
	0xce, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xdc, 0xb8,
	0x24, 0x1c, 0xf3, 0xf2, 0xf2, 0x4b, 0xf3, 0x92, 0x53, 0x03, 0x12, 0x2b, 0x73, 0x53, 0xf3, 0x4a,
	0x42, 0x32, 0x8a, 0x52, 0x8b, 0x33, 0xf2, 0x73, 0x52, 0x84, 0xb4, 0xb8, 0x04, 0xd0, 0xc5, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0x30, 0xc4, 0x9d, 0x64, 0x4e, 0x3c, 0x92, 0x63, 0xbc, 0xf0,
	0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8,
	0xf1, 0x58, 0x8e, 0x21, 0x8a, 0xa9, 0x20, 0x29, 0x89, 0x0d, 0x6c, 0xab, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x50, 0xca, 0x0e, 0x0a, 0x86, 0x00, 0x00, 0x00,
}

func (m *AnnouncePaymentThreshold) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AnnouncePaymentThreshold) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AnnouncePaymentThreshold) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintPricing(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *AnnouncePaymentThreshold) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovPricing(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozPricing(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AnnouncePaymentThreshold) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func skipPricing(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthPricing        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPricing          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPricing = fmt.Errorf("proto: unexpected end of group")
)
