// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pushsync.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Delivery struct {
	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Stamp   []byte `protobuf:"bytes,3,opt,name=Stamp,proto3" json:"Stamp,omitempty"`
}

func (m *Delivery) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Delivery) String() string            { _ = "STUB: not implemented"; return "" }
func (*Delivery) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Delivery) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Delivery) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Delivery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Delivery) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Delivery) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Delivery) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Delivery proto.InternalMessageInfo

func (m *Delivery) GetAddress() []byte { _ = "STUB: not implemented"; return nil }

func (m *Delivery) GetData() []byte { _ = "STUB: not implemented"; return nil }

func (m *Delivery) GetStamp() []byte { _ = "STUB: not implemented"; return nil }

type Receipt struct {
	Address       []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Signature     []byte `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Nonce         []byte `protobuf:"bytes,3,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Err           string `protobuf:"bytes,4,opt,name=Err,proto3" json:"Err,omitempty"`
	StorageRadius uint32 `protobuf:"varint,5,opt,name=StorageRadius,proto3" json:"StorageRadius,omitempty"`
}

func (m *Receipt) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Receipt) String() string            { _ = "STUB: not implemented"; return "" }
func (*Receipt) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Receipt) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Receipt) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Receipt) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Receipt) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Receipt) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetAddress() []byte { _ = "STUB: not implemented"; return nil }

func (m *Receipt) GetSignature() []byte { _ = "STUB: not implemented"; return nil }

func (m *Receipt) GetNonce() []byte { _ = "STUB: not implemented"; return nil }

func (m *Receipt) GetErr() string { _ = "STUB: not implemented"; return "" }

func (m *Receipt) GetStorageRadius() uint32 { _ = "STUB: not implemented"; return 0 }

func init() {
	proto.RegisterType((*Delivery)(nil), "pushsync.Delivery")
	proto.RegisterType((*Receipt)(nil), "pushsync.Receipt")
}

func init() { proto.RegisterFile("pushsync.proto", fileDescriptor_723cf31bfc02bfd6) }

var fileDescriptor_723cf31bfc02bfd6 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0x2d, 0xce,
	0x28, 0xae, 0xcc, 0x4b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xfc,
	0xb8, 0x38, 0x5c, 0x52, 0x73, 0x32, 0xcb, 0x52, 0x8b, 0x2a, 0x85, 0x24, 0xb8, 0xd8, 0x1d, 0x53,
	0x52, 0x8a, 0x52, 0x8b, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0x60, 0x5c, 0x21, 0x21,
	0x2e, 0x16, 0x97, 0xc4, 0x92, 0x44, 0x09, 0x26, 0xb0, 0x30, 0x98, 0x2d, 0x24, 0xc2, 0xc5, 0x1a,
	0x5c, 0x92, 0x98, 0x5b, 0x20, 0xc1, 0x0c, 0x16, 0x84, 0x70, 0x94, 0xfa, 0x19, 0xb9, 0xd8, 0x83,
	0x52, 0x93, 0x53, 0x33, 0x0b, 0x4a, 0xf0, 0x98, 0x27, 0xc3, 0xc5, 0x19, 0x9c, 0x99, 0x9e, 0x97,
	0x58, 0x52, 0x5a, 0x94, 0x0a, 0x35, 0x14, 0x21, 0x00, 0x32, 0xd9, 0x2f, 0x3f, 0x2f, 0x39, 0x15,
	0x66, 0x32, 0x98, 0x23, 0x24, 0xc0, 0xc5, 0xec, 0x5a, 0x54, 0x24, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1,
	0x19, 0x04, 0x62, 0x0a, 0xa9, 0x70, 0xf1, 0x06, 0x97, 0xe4, 0x17, 0x25, 0xa6, 0xa7, 0x06, 0x25,
	0xa6, 0x64, 0x96, 0x16, 0x4b, 0xb0, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0xa1, 0x0a, 0x3a, 0xc9, 0x9c,
	0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31,
	0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x14, 0x53, 0x41, 0x52, 0x12, 0x1b, 0x38,
	0x40, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x80, 0xc6, 0x9e, 0x01, 0x22, 0x01, 0x00, 0x00,
}

func (m *Delivery) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Delivery) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Delivery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Receipt) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Receipt) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Receipt) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintPushsync(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *Delivery) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Receipt) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovPushsync(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozPushsync(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Delivery) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Receipt) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipPushsync(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthPushsync        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPushsync          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPushsync = fmt.Errorf("proto: unexpected end of group")
)
