// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: retrieval.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Addr []byte `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
}

func (m *Request) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Request) String() string            { _ = "STUB: not implemented"; return "" }
func (*Request) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Request) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Request) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Request) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Request) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Request) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAddr() []byte { _ = "STUB: not implemented"; return nil }

type Delivery struct {
	Data  []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Stamp []byte `protobuf:"bytes,2,opt,name=Stamp,proto3" json:"Stamp,omitempty"`
	Err   string `protobuf:"bytes,3,opt,name=Err,proto3" json:"Err,omitempty"`
}

func (m *Delivery) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Delivery) String() string            { _ = "STUB: not implemented"; return "" }
func (*Delivery) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Delivery) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Delivery) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Delivery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Delivery) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Delivery) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Delivery) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Delivery proto.InternalMessageInfo

func (m *Delivery) GetData() []byte { _ = "STUB: not implemented"; return nil }

func (m *Delivery) GetStamp() []byte { _ = "STUB: not implemented"; return nil }

func (m *Delivery) GetErr() string { _ = "STUB: not implemented"; return "" }

func init() {
	proto.RegisterType((*Request)(nil), "retrieval.Request")
	proto.RegisterType((*Delivery)(nil), "retrieval.Delivery")
}

func init() { proto.RegisterFile("retrieval.proto", fileDescriptor_fcade0a564e5dcd4) }

var fileDescriptor_fcade0a564e5dcd4 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4a, 0x2d, 0x29,
	0xca, 0x4c, 0x2d, 0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0xc9, 0x72, 0xb1, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0x38, 0xa6,
	0xa4, 0x14, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x81, 0xd9, 0x4a, 0x6e, 0x5c, 0x1c, 0x2e,
	0xa9, 0x39, 0x99, 0x65, 0xa9, 0x45, 0x95, 0x20, 0x79, 0x97, 0xc4, 0x92, 0x44, 0x98, 0x3c, 0x88,
	0x2d, 0x24, 0xc2, 0xc5, 0x1a, 0x5c, 0x92, 0x98, 0x5b, 0x20, 0xc1, 0x04, 0x16, 0x84, 0x70, 0x84,
	0x04, 0xb8, 0x98, 0x5d, 0x8b, 0x8a, 0x24, 0x98, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x27,
	0x99, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63,
	0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c, 0x96, 0x63, 0x88, 0x62, 0x2a, 0x48, 0x4a, 0x62,
	0x03, 0x3b, 0xcb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x82, 0x88, 0x0a, 0x3c, 0xa9, 0x00, 0x00,
	0x00,
}

func (m *Request) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Request) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Request) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Delivery) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Delivery) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Delivery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintRetrieval(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *Request) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Delivery) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovRetrieval(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozRetrieval(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Request) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Delivery) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipRetrieval(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthRetrieval        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRetrieval          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRetrieval = fmt.Errorf("proto: unexpected end of group")
)
