// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pseudosettle.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Payment struct {
	Amount []byte `protobuf:"bytes,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (m *Payment) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Payment) String() string            { _ = "STUB: not implemented"; return "" }
func (*Payment) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Payment) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Payment) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Payment) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Payment) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Payment) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetAmount() []byte { _ = "STUB: not implemented"; return nil }

type PaymentAck struct {
	Amount    []byte `protobuf:"bytes,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (m *PaymentAck) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PaymentAck) String() string            { _ = "STUB: not implemented"; return "" }
func (*PaymentAck) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PaymentAck) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PaymentAck) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PaymentAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PaymentAck) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PaymentAck) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PaymentAck) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PaymentAck proto.InternalMessageInfo

func (m *PaymentAck) GetAmount() []byte { _ = "STUB: not implemented"; return nil }

func (m *PaymentAck) GetTimestamp() int64 { _ = "STUB: not implemented"; return 0 }

func init() {
	proto.RegisterType((*Payment)(nil), "pseudosettle.Payment")
	proto.RegisterType((*PaymentAck)(nil), "pseudosettle.PaymentAck")
}

func init() { proto.RegisterFile("pseudosettle.proto", fileDescriptor_3ff21bb6c9cf5e84) }

var fileDescriptor_3ff21bb6c9cf5e84 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0x4e, 0x2d,
	0x4d, 0xc9, 0x2f, 0x4e, 0x2d, 0x29, 0xc9, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x41, 0x16, 0x53, 0x52, 0xe4, 0x62, 0x0f, 0x48, 0xac, 0xcc, 0x4d, 0xcd, 0x2b, 0x11, 0x12, 0xe3,
	0x62, 0x73, 0xcc, 0xcd, 0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x82, 0xf2,
	0x94, 0x9c, 0xb8, 0xb8, 0xa0, 0x4a, 0x1c, 0x93, 0xb3, 0x71, 0xa9, 0x12, 0x92, 0xe1, 0xe2, 0x0c,
	0xc9, 0xcc, 0x4d, 0x2d, 0x2e, 0x49, 0xcc, 0x2d, 0x90, 0x60, 0x52, 0x60, 0xd4, 0x60, 0x0e, 0x42,
	0x08, 0x38, 0xc9, 0x9c, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c,
	0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x14, 0x53, 0x41,
	0x52, 0x12, 0x1b, 0xd8, 0x65, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x87, 0xcb, 0xb8, 0x18,
	0xaf, 0x00, 0x00, 0x00,
}

func (m *Payment) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Payment) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Payment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PaymentAck) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *PaymentAck) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *PaymentAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintPseudosettle(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *Payment) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PaymentAck) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovPseudosettle(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozPseudosettle(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Payment) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PaymentAck) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipPseudosettle(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthPseudosettle        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPseudosettle          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPseudosettle = fmt.Errorf("proto: unexpected end of group")
)
